version: '3.8'

services:
  app:
    build: .
    ports:
      - "5200:5200"
    volumes:
      - /Volumes/Andrew/images:/images
    environment:
      - PORT=5200
      - IMAGES_DIR=/images
    networks:
      - proxy_network
    restart: unless-stopped

networks:
  proxy_network:
    external: true
    name: proxy_network
