version: '3.8'

services:
  app:
    build: .
    ports:
      - "5200:5200"
    volumes:
      - /Users/andrewlim/Desktop/Mohe/images:/images
    environment:
      - PORT=5200
      - IMAGES_DIR=/images
